server:
  port: 80 # 端口设置
spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # 使用服务发现路由
          lower-case-service-id: true
      enabled: true # 开启网关，默认是开启的
      routes: # 设置路由，注意是数组，可以设置多个，按照id分割
        - id: service-hosp # 路由id，没有要求，唯一即可
          uri: lb://service-hosp # 设置真正的服务(应用名称) 也可以填http://localhost:8201
          predicates:
            - Path=/*/hosp/**
        - id: service-cmn # 路由id，没有要求，唯一即可
          uri: lb://service-cmn # 设置真正的服务(应用名称) 也可以填http://localhost:8201
          predicates:
              - Path=/*/cmn/**
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos

